require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp")
require("core.plugin_config.cmp")
require("core.plugin_config.toggleterm")
require("core.plugin_config.mason-lsp")
